# Generated by Django 5.2.3 on 2025-08-09 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="bathrooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="bedrooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="property",
            name="date_listed",
            field=models.DateTimeField(auto_now_add=True, default="2025-1-1"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="property",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="property",
            name="listing_type",
            field=models.CharField(
                choices=[("sale", "For Sale"), ("rent", "For Rent")],
                default="sale",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("apartment", "Apartment"),
                    ("condo", "Condominium"),
                    ("townhouse", "Townhouse"),
                    ("land", "Land"),
                ],
                default="house",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="property",
            name="square_feet",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
