# Generated by Django 5.2.3 on 2025-08-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0002_property_bathrooms_property_bedrooms_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="listing_type",
            field=models.CharField(
                choices=[("sale", "For Sale"), ("rent", "For Rent")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("house", "House"),
                    ("apartment", "Apartment"),
                    ("condo", "Condominium"),
                    ("townhouse", "Townhouse"),
                    ("land", "Land"),
                ],
                max_length=20,
            ),
        ),
    ]
