# Generated by Django 5.2.3 on 2025-11-26 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0005_propertyimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inquiry",
            options={"ordering": ["-submitted_at"], "verbose_name_plural": "Inquiries"},
        ),
        migrations.AlterModelOptions(
            name="property",
            options={"ordering": ["-date_listed"], "verbose_name_plural": "Properties"},
        ),
        migrations.AddField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, null=True, unique=True),
        ),
    ]
