# Generated by Django 5.2.3 on 2025-11-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0006_alter_inquiry_options_alter_property_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property",
            name="slug",
            field=models.SlugField(blank=True, max_length=250, unique=True),
        ),
    ]
